version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    command: php vendor/bin/phpunit
    environment:
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    depends_on:
      - memcached
  memcached:
    image: memcached:1.6.10-alpine
